name: Rolling Update Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

    - name: Build and Push Backend Image
      run: |
        docker build -t bitscrunch/backend:latest ./backend
        docker push bitscrunch/backend:latest

    - name: Build and Push Frontend Image
      run: |
        docker build -t bitscrunch/frontend:latest ./frontend
        docker push bitscrunch/frontend:latest

    - name: Deploy to Kubernetes
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: |
        kubectl apply -f deploy/k8s-deployment.yaml
        kubectl rollout status deployment/bitscrunch-backend
        kubectl rollout status deployment/bitscrunch-frontend